FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# CloudService

CloudService is a simple API allowing users to define cloud products & services.

## Product Family Collection [/productfamilies]

### List All Product Families [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                isActive: 1
                name: "云主机"
                description: "虚拟主机"
                longDescription: null
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createdDate: null
                modifiedDate: null
                orderTemplate: null
                attributes: null
            }
        ]

### Create a New Product Family [POST]

You may create your own product family using this action. It takes a JSON
object containing a product family and its attributes

+ Request (application/json)

        {
            "name": "云硬盘",
            "isActive": 1
            description: "云硬盘，可以挂载到云主机上"
            longDescription: null
            unitSize: 1
            logo: null
            startingPriceHourly: 0.16
            startingPriceMonthly: 30            
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                id: 2
                isActive: 1
                name: "云硬盘"
                description: "云硬盘，可以挂载到云主机上"
                longDescription: null
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createdDate: null
                modifiedDate: null
                orderTemplate: null
                attributes: null
            }
