FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# CloudService

CloudService is a simple API allowing users to define cloud products & services.
Some basic data:
## Product Catalogue:
### Public catalogue
id = 1; name = “公共服务目录”

## Product Categories:
### Public category #1
id = 1; name = “主机与网络”
id = 2; name = “存储”
id = 3; name = “行业应用”

## Product Family:
### Public Family #1
id = 1; name = "云主机"; categoryId = 1
### Public Family #2
id = 2; name = "云硬盘"; categoryId = 2
### Public Family #3
id = 3; name = "公网IP"; categoryId = 1
### Public Family #4
id = 4; name = "对象存储"; categoryId = 2
### Public Family #5
id = 5; name = "CDN"; categoryId = 2

## Product Item Category:
### Public Item Category #1
id = 1; name = "CPU"
### Public Item Category #2
id = 2; name = "MEMORY"
### Public Item Category #3
id = 3; name = "OS"
### Public Item Category #4
id = 4; name = "ROOT_DISK"
### Public Item Category #5
id = 5; name = "DISK"
### Public Item Category #6
id = 6; name = "PUBLIC_IP"


## Product Item Category Group
### Public Item Category #1
id = 1; name = "CPU"; categoryId = 1;
### Public Item Category #2
id = 2; name = "MEMORY"; categoryId = 2;
### Public Item Category #3
id = 3; name = "OS"; categoryId = 3;
### Public Item Category #4
id = 4; name = "ROOT_DISK"; categoryId = 4;
### Public Item Category #5
id = 5; name = "DISK_NORMAL_IO"; categoryId = 5;
id = 6; name = "DISK_HIGH_IO"; categoryId = 5;
### Public Item Category #6
id = 7; name = "PUBLIC_IP"; categoryId = 6;


## Product Item:
### Public Item #10
id = 10; keyName = "CPU_2C"; groupId = 1;
### Public Item #20
id = 20; keyName = "MEM_4G"; groupId = 2;
### Public Item #30
id = 30; name = "CENTOS_5.6_64bit"; groupId = 3;
### Public Item #40
id = 40; name = "ROOT_DISK_WIN_40G"; groupId = 4;
id = 41; name = "ROOT_DISK_LINUX_20G"; groupId = 4;
### Public Item #50
id = 50; name = "DISK_100G"; groupId = 5;
### Public Item #60
id = 60; name = "PUBLIC_IP_FIXED"; groupId = 6;
id = 61; name = "PUBLIC_IP_METERED"; groupId = 6;

## Product Family Collection [/productfamilies]

### List All Product Families [GET]
+ Response 200 (application/json)

        [
            {
                id: 1
                isActive: 1
                name: "云主机"
                description: "虚拟主机"
                longDescription: null
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                createdBy: 1
                updatedBy: 1
                orderTemplate: null
                attributes: null
            }
        ]

### Create a New Product Family [POST]

You may create your own product family using this action. It takes a JSON
object containing a product family and its attributes

+ Request (application/json)

        {
            "name": "云硬盘",
            "isActive": 1
            description: "云硬盘，可以挂载到云主机上"
            longDescription: null
            unitSize: 1
            logo: null
            startingPriceHourly: 0.16
            startingPriceMonthly: 30            
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                id: 2
                isActive: 1
                name: "云硬盘"
                description: "云硬盘，可以挂载到云主机上"
                longDescription: null
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                createdBy: 1,
                updatedBy: 1,
                orderTemplate: null
                attributes: null
            }

## Product Family [/productfamilies/{id}]
+ Parameters
    + id (required, number, `1`) 
### Get One product family details [GET]
+ Response 200 (application/json)

        [
            {
                id: 1
                isActive: 1
                name: "云主机"
                description: "虚拟主机"
                longDescription: null
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                createdBy: 1
                updatedBy: 1
                orderTemplate: null
                attributes: null
            }
        ]

## Product Catalogue Collection [/productcatalogues]
### List All Product Catalogues [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                isPublic: 1
                name: "公共服务目录"
                description: "公共服务目录"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                createdBy: 1,
                updatedBy: 1
            }
        ]
## Product Category Collection [/productcategories]

### List All Product Catelogues [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                isActive: 1
                name: "主机与网络"
                description: "主机与网络"
                logo: null
                sort: 1
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
            },
            {
                id: 2
                isActive: 1
                name: "存储"
                description: "虚拟存储"
                logo: null
                sort: 2
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
            }

        ]

## Product Inventory Collection [/productinventories]

### List All Product Inventories [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                itemId: 10
                regionId: 1
                availableInventoryCount: NULL
                availableInventoryCapacity: 1000
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createdDate: null
                modifiedDate: null
                orderTemplate: null
                attributes: null
            }
        ]
## Product Item Category Collection [/productitemcategories]

### List All Product Categories [GET]
### Public Item Category #1

+ Response 200 (application/json)

        [
            {
                id: 1
                categoryCode: "CPU"
                name: "CPU"
                quantityLimit: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                categorygroups:[
                    {
                        id: 1,
                        name: "CPU"
                    }                  
                ]
            },
            {
                id: 2
                categoryCode: "MEM"
                name: "MEMORY"
                quantityLimit: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
                categorygroups:[
                    {
                        id: 2,
                        name: "MEMORY"
                    }                  
                ]
            },            
            {
                id: 3
                categoryCode: "OS"
                name: "Operation System"
                quantityLimit: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
                categorygroups:[
                    {
                        id: 3,
                        name: "OS"
                    }                  
                ]
            }, 
            {
                id: 4
                categoryCode: "ROOT_DISK"
                name: "Root Disk"
                quantityLimit: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
                categorygroups:[
                    {
                        id: 4,
                        name: "ROOT_DISK"
                    }                  
                ]
            },
            {
                id: 5
                categoryCode: "DISK"
                name: "DISK"
                quantityLimit: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
                categorygroups:[
                    {
                        id: 5,
                        name: "DISK_NORMAL_IO"
                    },
                    {
                        id: 6,
                        name: "DISK_HIGH_IO"
                    } 
                ]
            },
            {
                id: 6
                categoryCode: "PUBLIC_IP"
                name: "Public IP"
                quantityLimit: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
                categorygroups:[
                    {
                        id: 7,
                        name: "PUBLIC_IP"
                    }
                ]
            }
        ]

## Product Item Category Group Collection [/productitemcategorygroups]

### List All Product Category Groups [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                name: "CPU"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 2
                name: "MEMORY"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 3
                name: "OS"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 4
                name: "ROOT_DISK"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 5
                name: "DISK_NORMAL_IO"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 6
                name: "DISK_HIGH_IO"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 7
                name: "PUBLIC_IP"
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            }
        ]

## Product Item Price Collection [/productitemprices]

### List All Product Item Prices [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                isActive: 1
                name: "云主机"
                description: "虚拟主机"
                longDescription: null
                unitSize: 1
                logo: null
                startingPriceHourly: 0.16
                startingPriceMonthly: 30
                createdDate: null
                modifiedDate: null
                orderTemplate: null
                attributes: null
            }
        ]

## Region Collection [/regions]

### List All Regions [GET]

+ Response 200 (application/json)

        [
            {
                id: 1,
                name: "北京1区",
                description: "",
                serviceProviderId: 1,
                locationId: 1,
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            },
            {
                id: 2,
                name: "北京2区",
                description: "",
                serviceProviderId: 1,
                locationId: 1,
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            }
        ]

## Location Collection [/locations]

### List All Locations [GET]

+ Response 200 (application/json)

        [
            {
                id: 1,
                name: "北京",
                description: "",
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                regions:
                [
                    {
                    id: 1,
                    name: "北京1区",
                    description: "",
                    serviceProviderId: 1,
                    },
                    {
                    id: 2,
                    name: "北京2区",
                    description: "",
                    serviceProviderId: 1,
                    }                    
                ]
            }
        ]

## Service Provider Collection [/serviceproviders]

### List All Service Providers [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                name: "惠普云平台"
                description: ""
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11",
                regions:
                [
                    {
                        id: 1,
                        name: "北京1区",
                        description: ""
                    },
                    {
                        id: 2,
                        name: "北京2区",
                        description: ""
                    }                    
                ]
            }
        ]

## Software Description Collection [/swdescriptions]

### List All Software Descriptioins [GET]

+ Response 200 (application/json)

        [
            {
                id: 1
                licenseTerm: 1
                name: ""
                description: ""
                longDescription: null
                manufacture: ""
                OS: ""
                version: 5.2
                virtualLicense: null
                virtualizationPlatform: null
                createDate:"2015-11-12 12:30:01",
                modifyDate:"2015-11-12 12:40:11"
            }
        ]
## Product Item Collection [/productItem]

### Query All Product Item By Region [GET]

+ Response 200 (application/json)

        [
            {
                "category_id": "101",
                "category_name": "CPU",
                "category_group": [
                    {
                        "category_group_id": "101001",
                        "category_group_name": "CPU",
                        "priduct_item": [
                            {
                                "product_item_id": "1010010001",
                                "product_item_name": "1C",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1010010002",
                                "product_item_name": "2C",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1010010003",
                                "product_item_name": "4C",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1010010004",
                                "product_item_name": "8C",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            }
                        ]
                    }
                ],
                "quantity": "1"
            },
            {
                "category_id": "102",
                "category_name": "Memory",
                "category_group": [
                    {
                        "category_group_id": "102001",
                        "category_group_name": "Memory",
                        "priduct_item": [
                            {
                                "product_item_id": "1020010001",
                                "product_item_name": "1G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1020010002",
                                "product_item_name": "2G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1020010003",
                                "product_item_name": "4G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1020010004",
                                "product_item_name": "8G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            }
                        ]
                    }
                ],
                "quantity": "1"
            },
            {
                "category_id": "103",
                "category_name": "Disk",
                "category_group": [
                    {
                        "category_group_id": "103001",
                        "category_group_name": "DISK_NORMAL_IO",
                        "priduct_item": [
                            {
                                "product_item_id": "1030010001",
                                "product_item_name": "10G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1030010002",
                                "product_item_name": "20G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1030010003",
                                "product_item_name": "30G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1030010004",
                                "product_item_name": "40G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            }
                        ]
                    },
                    {
                        "category_group_id": "103002",
                        "category_group_name": "DISK_HIGH_IO",
                        "priduct_item": [
                            {
                                "product_item_id": "1030020001",
                                "product_item_name": "10G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1030020002",
                                "product_item_name": "20G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1030020003",
                                "product_item_name": "30G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            },
                            {
                                "product_item_id": "1030020004",
                                "product_item_name": "40G",
                                "product_item_price": {
                                    "hourly_recurring_fee": "100",
                                    "labor_fee": "50",
                                    "one_time_fee": 0.34,
                                    "monthly_recurring_fee": 1.2,
                                    "recurring_fee_tax": "0.99",
                                    "usageRate": "0.5"
                                }
                            }
                        ]
                    }
                ],
                "quantity": "4"
            }
        ]

# Bazaar Order API

Order API for Bazaar project.

## Create Order [/placeOrder]

### Create order[POST]

Create order instance with input configuration parameters. 
The verifyOrder will use with the same method.

+ Request (application/json)

        {
            "parameters" : [
                {
                    "packageId" : 126,
                    "location" :449494,
                    "locationObject": {
                        "id": 449494,
                        "longName": "北京1区",
                        "name": "BJ01"
                    },
                    "quantity" : 1,
                    "hardware": [{
                        "hostname": "TEST",
                        "domain": "test1"
                    }],
                    "orderConfiguration": [
                        {"productId": 13739}, //Single Processor Quad Core Xeon 1270 - 3.40GHz (Sandy Bridge) - 1 x 8MB cache w/H
                        {"productId": 13748}, //32 GB DDR3 1333
                        {"productId": 1267},  //1TB sataII
                        {"productId": 342},  //2000 GB Bandwidth
                        {"productId": 21141}, //1 Gbps Dual public uplink
                        {"productId": 876}, //Non-Raid Disk Controller
                        {"productId": 21},  //single primary ip
                        {"productId": 37620}  //Ubuntu 14.04 64bit
                    ],
                    "serviceOperation":[
                        {"serviceOperationId":"10001", [{"param","value"},{"param2","value2"}]} // binding disk
                    ]
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /placeOrder

    + Body

            {
                "billingOrderItemId": “100001”,
                "hardware": [
                    {
                        "accountId": null,
                        "domain": "test1",
                        "hardwareStatusId": null,
                        "hostname": "TEST",
                    }
                ],
                "location": "449494",
                "locationObject": {
                    "id": 449494,
                    "longName": "北京1区",
                    "name": "BJ01"
                },
                "paymentType": "1",  // pay by account's fund
                "orderConfiguration": [
                    {
                        "categories": [
                            {
                                "categoryCode": "server",
                                "id": 1,
                                "name": "Server"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 13739,
                        "item": {
                            "bundle": [],
                            "capacity": "3.4",
                            "description": "Single Intel Xeon E3-1270 (4 Cores, 3.40 GHz)",
                            "id": 3796,
                            "keyName": "INTEL_SINGLE_XEON_1270_3_40_2",
                            "units": "GHz"
                        },
                        "itemId": 3796,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "ram",
                                "id": 3,
                                "name": "RAM"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 13748,
                        "item": {
                            "bundle": [],
                            "capacity": "32",
                            "description": "32 GB DDR3 1333",
                            "id": 3805,
                            "keyName": "RAM_32_GB_DDR3_1333_NON_REG",
                            "units": "GB"
                        },
                        "itemId": 3805,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "disk0",
                                "id": 4,
                                "name": "First Hard Drive"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 1267,
                        "item": {
                            "bundle": [],
                            "capacity": "500",
                            "description": "500 GB SATA ",
                            "id": 14,
                            "keyName": "HARD_DRIVE_500GB_SATA_II",
                            "units": "GB"
                        },
                        "itemId": 14,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "bandwidth",
                                "id": 10,
                                "name": "Public Bandwidth"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 342,
                        "item": {
                            "bundle": [],
                            "capacity": "20000",
                            "description": "20000 GB Bandwidth",
                            "id": 249,
                            "keyName": "BANDWIDTH_20000_GB",
                            "units": "GB"
                        },
                        "itemId": 249,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "port_speed",
                                "id": 26,
                                "name": "Uplink Port Speeds"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 21141,
                        "item": {
                            "bundle": [
                                {
                                    "bundleItem": {
                                        "capacity": "1000",
                                        "description": "1 Gbps Dual Public & Private Network Uplinks (Unbonded)",
                                        "id": 4263,
                                        "keyName": "1_GBPS_DUAL_PUBLIC_PRIVATE_NETWORK_UPLINKS_UNBONDED",
                                        "units": "Mbps"
                                    },
                                    "bundleItemId": 4263,
                                    "category": {
                                        "categoryCode": "service_port",
                                        "id": 9,
                                        "name": "Private Network Port"
                                    },
                                    "id": 5544,
                                    "itemPrice": {
                                        "id": 22235,
                                        "itemId": 4399,
                                        "oneTimeFee": "0",
                                        "recurringFee": "0",
                                    },
                                    "itemPriceId": 22235
                                },
                                {
                                    "bundleItem": {
                                        "capacity": "1000",
                                        "description": "1 Gbps Dual Public & Private Network Uplinks (Unbonded)",
                                        "id": 4263,
                                        "keyName": "1_GBPS_DUAL_PUBLIC_PRIVATE_NETWORK_UPLINKS_UNBONDED",
                                        "units": "Mbps"
                                    },
                                    "bundleItemId": 4263,
                                    "category": {
                                        "categoryCode": "public_port",
                                        "id": 8,
                                        "name": "Public Network Port"
                                    },
                                    "id": 6400,
                                    "itemPrice": {
                                        "hourlyRecurringFee": "0",
                                        "id": 22233,
                                        "itemId": 4400,
                                        "oneTimeFee": "0",
                                        "recurringFee": "0",
                                    },
                                    "itemPriceId": 22233
                                }
                            ],
                            "capacity": "1000",
                            "description": "1 Gbps Dual Public & Private Network Uplinks (Unbonded)",
                            "id": 4263,
                            "keyName": "1_GBPS_DUAL_PUBLIC_PRIVATE_NETWORK_UPLINKS_UNBONDED",
                            "units": "Mbps"
                        },
                        "itemId": 4263,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "response",
                                "id": 22,
                                "name": "Response"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 58,
                        "item": {
                            "bundle": [],
                            "description": "Automated Notification",
                            "id": 52,
                            "keyName": "AUTOMATED_NOTIFICATION"
                        },
                        "itemId": 52,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "disk_controller",
                                "id": 11,
                                "name": "Disk Controller"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 876,
                        "item": {
                            "bundle": [],
                            "description": "Non-RAID",
                            "id": 487,
                            "keyName": "DISK_CONTROLLER_NONRAID"
                        },
                        "itemId": 487,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "pri_ip_addresses",
                                "id": 13,
                                "name": "Primary IP Addresses"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 21,
                        "item": {
                            "bundle": [],
                            "capacity": "1",
                            "description": "1 IP Address",
                            "id": 15,
                            "keyName": "1_IP_ADDRESS"
                        },
                        "itemId": 15,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    },
                    {
                        "categories": [
                            {
                                "categoryCode": "os",
                                "id": 12,
                                "name": "Operating System"
                            }
                        ],
                        "hourlyRecurringFee": "0",
                        "id": 37620,
                        "item": {
                            "bundle": [],
                            "capacity": "0",
                            "description": "Ubuntu Linux 14.04 LTS Trusty Tahr - Minimal Install (64 bit)",
                            "id": 4710,
                            "keyName": "OS_UBUNTU_14_04_LTS_TRUSTY_TAHR_MINIMAL_64_BIT_2",
                            "units": "N/A"
                        },
                        "itemId": 4710,
                        "oneTimeFee": "0",
                        "recurringFee": "0",
                    }
                ],
                "primaryDiskPartitionId": 1,
                "quantity": 1,
                "resourceGroupId": null,
                "resourceGroupTemplateId": null,
                "serverCoreCount": 4,
                "sourceVirtualGuestId": null,
                "useHourlyPricing": false
            }
        
      
## Order family [/orders]

### List All Orders [GET]
+ Request (application/json)

        {
            "accountId"="10001";
            "customerId":="100010";
        }
        
+ Response 200 (application/json)

        [
            {
                "orderId":"10001",
                "accountId": "10001",  //The account to which an order belongs.
                "customerId": "100010", //The user id who deals this order
                "status": "5" ,//
                "payStatus" : "3",
                "createDate":"2015-11-12 12:30:01",
                "modifyDate":"2015-11-12 12:40:11",
                "payedDate":"2015-11-12 12:41:02",
                "expirationDate":"",
                "cancelledDate":"",
                "totalAmount":"90.00", //
                "payAmount":"90.00",
                
                "orderItems": [
                    {
                        "categoryId": "10001",
                        {
                            "categoryCode": "server",
                            "id": "10001",
                            "name": "云主机"
                        },
                        "displayProductName": "云服务器（包年包月）"，
                        "orderConfiguration":[
                            {
                                "productItemId":"13739",
                                "productName":"Single Processor Quad Core Xeon 1270 - 3.40GHz",
                                "priceHourly":"0.10",
                                "priceMonthly":"3.00",
                                "usage":"3.00",
                                "sortId":"1",
                            },
                            {
                                "productItemId":"13748",
                                "productName":"32 GB DDR3 1333",
                                "priceHourly":"0.00",
                                "priceMonthly":"0.00",
                                "usage":"0.00",
                                "sortId":"2"
                            },
                            {
                                "productItemId":"37620",
                                "productName":"buntu 14.04 64bit",
                                "priceHourly":"0.00",
                                "priceMonthly":"0.00",
                                "usage":"0.00",
                                "sortId":"3"
                            },
                            {
                                "productId":"1267",
                                "productName":"1TB sataII",
                                "priceHourly":"0.0",
                                "priceMonthly":"0.0",
                                "sortId":"4"
                            }
                            {
                                "productItemId":"342",
                                "productName":"2000 GB Bandwidth",
                                "priceHourly":"0.00",
                                "priceMonthly":"0.00",
                                "usage":"0.00",
                                "sortId":"5"
                            },
                            {
                                "productItemId":"21141",
                                "productName":"1 Gbps Dual public uplink",
                                "priceHourly":"0.00",
                                "priceMonthly":"0.00",
                                "usage":"0.00",
                                "sortId":"6",
                                "hidden":"true"
                            },
                        ],
                        "quantity":"1",
                        "orderPeriod":"12", // one year
                        "priceHourly":"0.1",
                        "priceMonthly":"30.00",
                        "startDate": "2015-11-12 12:42:02",
                        "endDate":"2016-11-12 12:42:02",
                        "chargeModel":"FLAT",
                        "totalAmount":"90.00",
                        "billingItems":[
                            {
                                "billingItemId":"1000001",
                                "activeFalg":"true",
                                "billingPackages":[
                                    {
                                        "billingPackageId":"1000001", 
                                        "subscriptionId":"100001",
                                        "description":"包年包月云主机",
                                        "priceHourly":"0.1",
                                        "priceMonthly":"30",
                                        "cycleStartDate":"2015-11-12 12:42:02",
                                        "hoursUsed":"50",
                                        "lastBillDate":"2015-11-12 12:42:02",
                                        "nextBillDate":"2016-11-12 12:42:02",
                                        "activeFlag":"true",
                                        "chargeModel":"FLAT",
                                        "modifyDate": "2015-11-12 12:42:02"
                                        "uniqueResourceId":"e9f696b3-7ce7-42a8-9eb7-318aeec1acf4"
                                    },
                                    {
                                        "billingPackageId":"1000002"
                                        "subscriptioId":"100002",
                                        "description":"1TB sataII硬盘",
                                        "priceHourly":"0.01",
                                        "priceMonthly":"3",
                                        "cycleStartDate":"2015-11-12 12:42:02",
                                        "hoursUsed":"50",
                                        "lastBillDate":"2015-11-12 12:42:02",
                                        "nextBillDate":"2016-11-12 12:42:02",
                                        "activeFlag":"true",
                                        "chargeModel":"FLAT",
                                        "modifyDate": "2015-11-12 12:42:02"
                                        "uniqueResourceId":"9b04ad7e-6d97-40bf-9d62-57873382eab0"
                                    }
                                ]
                            }
                        ],
                        
                    }
                ]
            }
        ]

  
## Detail Order info [/orderdetail]
## Get Order collection by account id [/getOrdersByAccount]
## Get Biill Item collection by account id [/getBillItemsByAccount]



